### ISSUE TITLE
Please explain why premissions are required.

### ISSUE THREAD

**Issue by jcc10** [moncefplastin07/deno-zip#1]
Could you please add in why given permissions are required?

* **--allow-run** What is being run?
* **--allow-env** Why is the env being accessed?
* **--unstable** What unstable API is being used?

**Comment by moncefplastin07** [comment]
Thank you for your interest in helping to develop this tool
As for your question, you should know that these tools depend on decompressing via the system command prompt only and do not use any external tools or deno built-in function ..
--allow-run : for running unzipping command in command prompt
--allow-env : Just added it by mistake, I just added it by mistake .. it should be in its place --allow-read to check the existence of the file before starting the decompression process.
--unstable : Because I use a slightly old version of the standard Deno modules that contain some of the more unstable features

**Comment by jcc10** [comment]
Thank you. I would probably add those details into the readme since there are some situations where you may want to use the command prompt and some where you might want to load the file and use a wasm to un-zip.

**Comment by moncefplastin07** [comment]
Thank you so much, I fixed these errors in  v1.1.1 You can check back now .. We thank you again for your interest
